### ISSUE TITLE
Better webpage Styling - CSS

### ISSUE THREAD

**Issue by MichaelBarney** [MichaelBarney/FB-Messenger-Get-Started-Button#1]
We need to make this website look a little better....

Feel free to make it look as nice as you want!

**Comment by Zubair-12** [comment]
Hi I am a beginner. Can you guide me about these.

**Comment by MichaelBarney** [comment]
You can create a .css file for this website and make it look a bit nicer

**Comment by CilgaIscan** [comment]
I would like to work on this project :) @MichaelBarney

**Comment by Divyanshwick** [comment]
I would like to contribute to this issue.

**Comment by MichaelBarney** [comment]
@CilgaIscan @Divyanshwick , feel free to contribute!

**Comment by reecealanboyd** [comment]
linked html to stylesheet and styled button: https://github.com/MichaelBarney/FB-Messenger-Get-Started-Button/pull/2
